import React from "react";
import { createRoot } from "react-dom/client";
import Invitation, { inviterFromQuery } from "../app/invitation";
import { languageFromQuery, invitationMetadata } from "../lib/invitation-language";
import "../app/globals.css";
import "../app/family-design.css";
const query = new URLSearchParams(window.location.search);
const language=languageFromQuery(query.get("lang"));
const inviter=inviterFromQuery(query.get("inviter"));
document.title=invitationMetadata(language).title;
createRoot(document.getElementById("root")!).render(<div className={inviter ? "family-design" : undefined} lang={language} dir={language === "ar" ? "rtl" : "ltr"}><Invitation initialLanguage={language} inviter={inviter}/></div>);
